import type { Octokits } from "../github/api/client";
import {
  updateCommentBody,
  type CommentUpdateInput,
} from "../github/operations/comment-logic";
import {
  isPullRequestReviewCommentEvent,
  type ParsedGitHubContext,
} from "../github/context";
import { GITHUB_SERVER_URL } from "../github/api/config";
import { checkAndCommitOrDeleteBranch } from "../github/operations/branch-cleanup";
import { updateKiroComment } from "../github/operations/comments/update-kiro-comment";

export type UpdateCommentLinkParams = {
  commentId: number;
  kiroBranch?: string;
  baseBranch: string;
  triggerUsername?: string;
  context: ParsedGitHubContext;
  octokit: Octokits;
  /** Whether the Kiro CLI itself succeeded. */
  kiroSuccess: boolean;
  /** How long the CLI ran, used for the "finished in Xs" header. */
  durationMs?: number;
  /** Whether the preparation phase completed. */
  prepareSuccess: boolean;
  errorDetails?: string;
};

/**
 * Final pass over the tracking comment: replace the "working" marker with a
 * result header, attach the branch and "Create a PR" links, and clean up a
 * branch that turned out to be empty.
 */
export async function updateCommentLink(
  params: UpdateCommentLinkParams,
): Promise<void> {
  const {
    commentId,
    kiroBranch,
    baseBranch,
    triggerUsername,
    context,
    octokit,
  } = params;

  const { owner, repo } = context.repository;

  const serverUrl = GITHUB_SERVER_URL;
  const jobUrl = `${serverUrl}/${owner}/${repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;

  let comment;
  let isPRReviewComment = false;

  try {
    // Review comments and issue comments have separate id namespaces, so the
    // API has to match the event the comment was created for.
    if (isPullRequestReviewCommentEvent(context)) {
      console.log(`Fetching PR review comment ${commentId}`);
      const { data: prComment } = await octokit.rest.pulls.getReviewComment({
        owner,
        repo,
        comment_id: commentId,
      });
      comment = prComment;
      isPRReviewComment = true;
    }

    if (!comment) {
      console.log(`Fetching issue comment ${commentId}`);
      const { data: issueComment } = await octokit.rest.issues.getComment({
        owner,
        repo,
        comment_id: commentId,
      });
      comment = issueComment;
      isPRReviewComment = false;
    }
  } catch (error) {
    console.error("Failed to fetch the tracking comment. Debug info:");
    console.error(`Comment ID: ${commentId}`);
    console.error(`Event name: ${context.eventName}`);
    console.error(`Entity number: ${context.entityNumber}`);
    console.error(`Repository: ${context.repository.full_name}`);
    throw error;
  }

  const currentBody = comment.body ?? "";

  const { shouldDeleteBranch, branchLink } = await checkAndCommitOrDeleteBranch(
    octokit,
    owner,
    repo,
    kiroBranch,
    baseBranch,
  );

  // Offer a pre-filled PR link when this run created a branch that has content.
  let prLink = "";
  if (kiroBranch && !shouldDeleteBranch) {
    const escape = (value: string) =>
      value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const prUrlPattern = new RegExp(
      `${escape(serverUrl)}\\/.+\\/compare\\/${escape(baseBranch)}\\.\\.\\.`,
    );

    if (!prUrlPattern.test(currentBody)) {
      try {
        const { data: comparison } =
          await octokit.rest.repos.compareCommitsWithBasehead({
            owner,
            repo,
            basehead: `${baseBranch}...${kiroBranch}`,
          });

        if (
          comparison.total_commits > 0 ||
          (comparison.files && comparison.files.length > 0)
        ) {
          const entityType = context.isPR ? "PR" : "Issue";
          const prTitle = encodeURIComponent(
            `${entityType} #${context.entityNumber}: Changes from Kiro`,
          );
          const prBody = encodeURIComponent(
            `This PR addresses ${entityType.toLowerCase()} #${context.entityNumber}\n\nGenerated by [kiro-action](https://github.com/takuaizu/Kiro-action)`,
          );
          const prUrl = `${serverUrl}/${owner}/${repo}/compare/${baseBranch}...${kiroBranch}?quick_pull=1&title=${prTitle}&body=${prBody}`;
          prLink = `\n[Create a PR](${prUrl})`;
        }
      } catch (error) {
        console.error("Error checking for changes in branch:", error);
        // A missing PR link is not worth failing the update over.
      }
    }
  }

  const actionFailed = !params.prepareSuccess || !params.kiroSuccess;

  const commentInput: CommentUpdateInput = {
    currentBody,
    actionFailed,
    executionDetails:
      params.durationMs !== undefined
        ? { duration_ms: params.durationMs }
        : null,
    jobUrl,
    branchLink,
    prLink,
    branchName: shouldDeleteBranch || !branchLink ? undefined : kiroBranch,
    triggerUsername,
    errorDetails: params.errorDetails,
  };

  const updatedBody = updateCommentBody(commentInput);

  try {
    await updateKiroComment(octokit.rest, {
      owner,
      repo,
      commentId,
      body: updatedBody,
      isPullRequestReviewComment: isPRReviewComment,
    });
    console.log(
      `✅ Updated ${isPRReviewComment ? "PR review" : "issue"} comment ${commentId} with the job link`,
    );
  } catch (updateError) {
    console.error(
      `Failed to update ${isPRReviewComment ? "PR review" : "issue"} comment:`,
      updateError,
    );
    throw updateError;
  }
}
